### ISSUE TITLE
There is no Programmer option under the Tools menu

### ISSUE THREAD

**Issue by zipeijun** [MrBlinky/Arduboy-homemade-package#19]
Arduino IDE 2.1.0 has no Programmer option under the Tools menu, Arduino IDE 1.8.19 behaves normally and is able to flash the bootloader.

**Arduino IDE 2.1.0**
<img width="386" alt="截屏2023-06-05 09 55 13" src="https://github.com/MrBlinky/Arduboy-homemade-package/assets/26513148/5ab786bc-ba9c-4b10-85f3-93001edec8c6">

**Arduino 1.8.19**
<img width="386" alt="截屏2023-06-05 09 56 11" src="https://github.com/MrBlinky/Arduboy-homemade-package/assets/26513148/154a6431-2dc0-4bb5-bd36-3e8c66aa4e89">

**Comment by MrBlinky** [comment]
Hi! this is a known issue. The Arduino 2.x IDE has different behaviour. I found out the new IDE needs it's own copy of programmers.txt file in the boards package folder (location of boards.txt) This will be fixed in the next update.

For now you can copy the programmers.txt file from .../hardware/arduino/avr to ...packages/arduboy-homemade/hardware/avr/1.3.8

**Comment by MrBlinky** [comment]
You also need to remove the cached files so the IDE 'sees' the changes.  Removing the folder .../AppData/Roaming/arduino-ide will be the easiest way to do this.

**Comment by zipeijun** [comment]
Thank you for your reply, I have solved this problem with Arduino 1.x
I am raising this issue to help others with the same problem, for which I have not found a solution online.
Hopefully, can add a note to REDEME to help others.

(I am not a native English speaker, so I hope I can express my meaning clearly)
